# Generated by Django 5.0.2 on 2024-02-29 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Licenca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('fornecedor', models.CharField(blank=True, max_length=200, null=True)),
                ('quantidade', models.IntegerField()),
                ('data_aquisicao', models.DateField()),
                ('data_expiracao', models.DateField(blank=True, null=True)),
                ('valor_unitario', models.FloatField()),
                ('valor_total', models.FloatField()),
            ],
        ),
    ]
