# Generated by Django 5.0.2 on 2024-03-01 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licenca',
            name='valor_total',
        ),
    ]
