# Generated by Django 5.0.2 on 2024-03-01 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0002_remove_licenca_valor_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenca',
            name='licenca',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
