# Generated by Django 5.0.2 on 2024-03-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0003_licenca_licenca'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenca',
            name='quantidade_total',
            field=models.IntegerField(null=True),
        ),
    ]
