# Generated by Django 5.0.2 on 2024-03-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0005_rename_quantidade_total_licenca_quantidade_disponivel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenca',
            name='quantidade_disponivel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='licenca',
            name='quantidade_utilizada',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
