# Generated by Django 5.0.2 on 2024-03-01 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0007_fornecedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenca',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licenca_fornecedor', to='sga.fornecedor'),
        ),
    ]
