# Generated by Django 5.0.2 on 2024-03-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0008_alter_licenca_fornecedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenca',
            name='data_aquisicao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
