# Generated by Django 5.0.2 on 2024-03-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0009_alter_licenca_data_aquisicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenca',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='sga/'),
        ),
    ]
